# Generated by Django 4.2.7 on 2023-11-30 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organ',
            options={},
        ),
        migrations.RemoveField(
            model_name='organ',
            name='name',
        ),
        migrations.AddField(
            model_name='organ',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='organ',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.organ')),
            ],
        ),
    ]
