# Generated by Django 4.2.7 on 2023-11-30 18:54

import back.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_alter_organ_options_remove_organ_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='organ',
        ),
        migrations.AddField(
            model_name='notification',
            name='name',
            field=models.CharField(default='DefaultName', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='phone_number',
            field=models.CharField(default='DefaultPhoneNumber', max_length=100),
        ),
        migrations.AddField(
            model_name='organ',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=back.models.uniq_name_upload),
        ),
    ]
