# Generated by Django 4.2.7 on 2023-12-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_remove_notification_organ_notification_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='phone_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
