# Generated by Django 4.2.7 on 2023-12-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_notification_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organ',
            name='image',
        ),
    ]
