# Generated by Django 4.2.7 on 2023-12-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0015_remove_customuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
